spring:
  application:
    name: warehouse-end
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/warehouse
  session:
    timeout: 86400 # session失效时间
server:
  port: 3000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除的值
      logic-not-delete-value: 0 # 逻辑w未删除的值
